server:
  port: 8765
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: ListTasks
          uri: http://localhost:8081/
          predicates:
            - Path=/serviceA/**
        - id: ListWorkers
          uri: http://localhost:8082/
          predicates:
            - Path=/serviceB/**
